/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package yazlab.pkg1;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ffeki
 */
public class Admin extends javax.swing.JFrame {

    Integer ID;
    String oldIsbn;
    int sayac = 1;
    int sayac2 = 1;
    int totalUsers;
    int totalBooks;

    /**
     * Creates new form Admin
     */
    public Admin() {
        initComponents();
        totalUsers = TotalUsers();
        totalBooks = TotalBooks();
        jL_SayfaNo.setText("1/" + totalUsers);
        jL_SayfaNo1.setText("1/" + totalBooks);
        ShowUsers();
    }

    int TotalBooks() {
        int sayi = 0;
        DbConnect db = new DbConnect();
        String sql = "SELECT COUNT(ISBN) as total FROM books";
        try {
            db.rs = db.st.executeQuery(sql);
            while (db.rs.next()) {
                sayi = db.rs.getInt("total");
            }
        } catch (SQLException ex) {
            Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
        }
        double x = (double) sayi / 30;
        int y = (int) Math.ceil(x);

        return y;
    }

    int TotalUsers() {
        int sayi = 0;
        DbConnect db = new DbConnect();
        String sql = "SELECT COUNT(ID) as total FROM users";
        try {
            db.rs = db.st.executeQuery(sql);
            while (db.rs.next()) {
                sayi = db.rs.getInt("total");
            }
        } catch (SQLException ex) {
            Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
        }
        double x = (double) sayi / 30;
        //System.out.println(x);
        int y = (int) Math.ceil(x);
        //System.out.println(y);
        return y;
    }

    public void ShowUsers() {
        String sql = "SELECT * FROM users LIMIT 30 OFFSET " + (sayac - 1) * 30;
        DefaultTableModel Tablo = (DefaultTableModel) jT_Users.getModel();

        DbConnect db = new DbConnect();

        try {
            db.rs = db.st.executeQuery(sql);
            Tablo.getDataVector().removeAllElements();

            while (db.rs.next()) {
                Tablo.addRow(new Object[]{db.rs.getInt("ID"), db.rs.getString("Username"), db.rs.getString("Password"), db.rs.getString("Location"), db.rs.getInt("Age")});
            }

        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    public void ShowBooks() {
        String sql = "SELECT * FROM books LIMIT 30 OFFSET " + (sayac2 - 1) * 30;
        DefaultTableModel Tablo = (DefaultTableModel) jT_Books.getModel();

        DbConnect db = new DbConnect();

        try {
            db.rs = db.st.executeQuery(sql);
            Tablo.getDataVector().removeAllElements();

            while (db.rs.next()) {
                Tablo.addRow(new Object[]{db.rs.getString("ISBN"), db.rs.getString("Title"), db.rs.getString("Author"), db.rs.getInt("Year"), db.rs.getString("Publisher"), db.rs.getString("ImgS"), db.rs.getString("ImgM"), db.rs.getString("ImgL")});
            }

        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        Users = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jT_Users = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        username = new javax.swing.JTextField();
        password = new javax.swing.JTextField();
        location = new javax.swing.JTextField();
        age = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jB_Sol = new javax.swing.JButton();
        jL_SayfaNo = new javax.swing.JLabel();
        jB_Sağ = new javax.swing.JButton();
        jT_Sayfa = new javax.swing.JTextField();
        jB_Git = new javax.swing.JButton();
        jB_First = new javax.swing.JButton();
        jB_Last = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        Books = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jT_Books = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        author = new javax.swing.JTextField();
        title = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        year = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        ısbn = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        publisher = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        imgs = new javax.swing.JTextField();
        imgm = new javax.swing.JTextField();
        imgl = new javax.swing.JTextField();
        jB_First1 = new javax.swing.JButton();
        jB_Sol1 = new javax.swing.JButton();
        jL_SayfaNo1 = new javax.swing.JLabel();
        jB_Sağ1 = new javax.swing.JButton();
        jB_Last1 = new javax.swing.JButton();
        jT_Sayfa1 = new javax.swing.JTextField();
        jB_Git1 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPane1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTabbedPane1MouseClicked(evt);
            }
        });

        jT_Users.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Username", "Password", "Location", "Age"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jT_Users.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jT_UsersMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jT_Users);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Password:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Username:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Location:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Age:");

        jButton1.setText("EKLE");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("GÜNCELLE");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("SİL");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jB_Sol.setText("<");
        jB_Sol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_SolActionPerformed(evt);
            }
        });

        jL_SayfaNo.setText("1/x");
        jL_SayfaNo.setToolTipText("");

        jB_Sağ.setText(">");
        jB_Sağ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_SağActionPerformed(evt);
            }
        });

        jB_Git.setText("Git");
        jB_Git.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_GitActionPerformed(evt);
            }
        });

        jB_First.setText("<<");
        jB_First.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_FirstActionPerformed(evt);
            }
        });

        jB_Last.setText(">>");
        jB_Last.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_LastActionPerformed(evt);
            }
        });

        jButton7.setForeground(new java.awt.Color(51, 51, 255));
        jButton7.setText("GERİ");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout UsersLayout = new javax.swing.GroupLayout(Users);
        Users.setLayout(UsersLayout);
        UsersLayout.setHorizontalGroup(
            UsersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UsersLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(UsersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(UsersLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 733, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addGroup(UsersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(UsersLayout.createSequentialGroup()
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(UsersLayout.createSequentialGroup()
                                .addGroup(UsersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel3)
                                    .addGroup(UsersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 84, Short.MAX_VALUE))
                                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(UsersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(UsersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(password, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(location, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(username, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(age, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(UsersLayout.createSequentialGroup()
                        .addComponent(jButton7)
                        .addGap(67, 67, 67)
                        .addComponent(jB_First)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jB_Sol)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jL_SayfaNo, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jB_Sağ)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jB_Last)
                        .addGap(36, 36, 36)
                        .addComponent(jT_Sayfa, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jB_Git)))
                .addContainerGap(46, Short.MAX_VALUE))
        );
        UsersLayout.setVerticalGroup(
            UsersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UsersLayout.createSequentialGroup()
                .addGroup(UsersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(UsersLayout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addGroup(UsersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(username, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(UsersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(password, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(UsersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(location, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(UsersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(age, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(131, 131, 131)
                        .addGroup(UsersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(UsersLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 514, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(UsersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(UsersLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(UsersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jB_Sol)
                            .addComponent(jL_SayfaNo)
                            .addComponent(jB_Sağ)
                            .addComponent(jT_Sayfa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jB_Git)
                            .addComponent(jB_First)
                            .addComponent(jB_Last))
                        .addContainerGap(26, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, UsersLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton7)
                        .addContainerGap())))
        );

        jTabbedPane1.addTab("Users", Users);

        jT_Books.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ISBN", "Book-Title", "Book-Author ", "Year-Of-Publication", "Publisher", "Image-URL-S", "Image-URL-M", "Image-URL-L"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jT_Books.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jT_BooksMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jT_Books);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("Title:");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("Author:");

        jButton4.setText("EKLE");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setText("Year:");

        jButton5.setText("GÜNCELLE");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setText("Publisher:");

        jButton6.setText("SİL");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel10.setText("ISBN:");

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel11.setText("IMG - M");

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel12.setText("IMG - S");

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel13.setText("IMG -L");

        jB_First1.setText("<<");
        jB_First1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jB_First1MouseClicked(evt);
            }
        });
        jB_First1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_First1ActionPerformed(evt);
            }
        });

        jB_Sol1.setText("<");
        jB_Sol1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_Sol1ActionPerformed(evt);
            }
        });

        jL_SayfaNo1.setText("1/x");
        jL_SayfaNo1.setToolTipText("");

        jB_Sağ1.setText(">");
        jB_Sağ1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_Sağ1ActionPerformed(evt);
            }
        });

        jB_Last1.setText(">>");
        jB_Last1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_Last1ActionPerformed(evt);
            }
        });

        jB_Git1.setText("Git");
        jB_Git1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_Git1ActionPerformed(evt);
            }
        });

        jButton8.setForeground(new java.awt.Color(51, 51, 255));
        jButton8.setText("GERİ");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout BooksLayout = new javax.swing.GroupLayout(Books);
        Books.setLayout(BooksLayout);
        BooksLayout.setHorizontalGroup(
            BooksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(BooksLayout.createSequentialGroup()
                .addGap(0, 12, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 799, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(BooksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(BooksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(BooksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(BooksLayout.createSequentialGroup()
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(ısbn, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(BooksLayout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(title, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(BooksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(BooksLayout.createSequentialGroup()
                                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(imgs, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BooksLayout.createSequentialGroup()
                                .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(publisher, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BooksLayout.createSequentialGroup()
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(year, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BooksLayout.createSequentialGroup()
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(author, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(BooksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(BooksLayout.createSequentialGroup()
                            .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jButton5)
                            .addGap(18, 18, 18)
                            .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(BooksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(BooksLayout.createSequentialGroup()
                                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(imgl, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(BooksLayout.createSequentialGroup()
                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(imgm, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(23, 23, 23))
            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, BooksLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton8)
                .addGap(148, 148, 148)
                .addComponent(jB_First1)
                .addGap(18, 18, 18)
                .addComponent(jB_Sol1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jL_SayfaNo1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jB_Sağ1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jB_Last1)
                .addGap(27, 27, 27)
                .addComponent(jT_Sayfa1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jB_Git1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        BooksLayout.setVerticalGroup(
            BooksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BooksLayout.createSequentialGroup()
                .addGroup(BooksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(BooksLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(BooksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ısbn, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(BooksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(title, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(BooksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(author, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(BooksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(year, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(BooksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(publisher, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(BooksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(imgs, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(BooksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(imgm, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(BooksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(imgl, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(BooksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(BooksLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 516, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(BooksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton8)
                    .addGroup(BooksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jB_First1)
                        .addComponent(jB_Sol1)
                        .addComponent(jL_SayfaNo1)
                        .addComponent(jB_Sağ1)
                        .addComponent(jB_Last1)
                        .addComponent(jT_Sayfa1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jB_Git1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Books", Books);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        DbConnect db = new DbConnect();
        db.UserUpdate(ID, username.getText(), password.getText(), Integer.parseInt(age.getText()), location.getText());
        ShowUsers();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        DbConnect db = new DbConnect();
        db.UserDelete(ID);
        ShowUsers();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        DbConnect db = new DbConnect();
        db.UserAdd(username.getText(), password.getText(), Integer.parseInt(age.getText()), location.getText());
        ShowUsers();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        DbConnect db = new DbConnect();
        db.BookAdd(ısbn.getText(), title.getText(), author.getText(), Integer.parseInt(year.getText()), publisher.getText(), imgs.getText(), imgm.getText(), imgl.getText());
        ShowBooks();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        DbConnect db = new DbConnect();
        //System.out.println(oldIsbn);
        db.BookUpdate(ısbn.getText(), title.getText(), author.getText(), Integer.parseInt(year.getText()), publisher.getText(), imgs.getText(), imgm.getText(), imgl.getText(), oldIsbn);
        ShowBooks();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        DbConnect db = new DbConnect();
        db.BookDelete(oldIsbn);
        ShowBooks();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jT_UsersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jT_UsersMouseClicked
        // TODO add your handling code here:
        ID = (Integer) jT_Users.getModel().getValueAt(jT_Users.getSelectedRow(), 0);
        username.setText((String) jT_Users.getModel().getValueAt(jT_Users.getSelectedRow(), 1));
        password.setText((String) jT_Users.getModel().getValueAt(jT_Users.getSelectedRow(), 2));
        location.setText((String) jT_Users.getModel().getValueAt(jT_Users.getSelectedRow(), 3));
        age.setText(String.valueOf(jT_Users.getModel().getValueAt(jT_Users.getSelectedRow(), 4)));
    }//GEN-LAST:event_jT_UsersMouseClicked

    private void jT_BooksMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jT_BooksMouseClicked
        // TODO add your handling code here:
        oldIsbn = (String) jT_Books.getModel().getValueAt(jT_Books.getSelectedRow(), 0);
        ısbn.setText((String) jT_Books.getModel().getValueAt(jT_Books.getSelectedRow(), 0));
        title.setText((String) jT_Books.getModel().getValueAt(jT_Books.getSelectedRow(), 1));
        author.setText((String) jT_Books.getModel().getValueAt(jT_Books.getSelectedRow(), 2));
        year.setText(String.valueOf(jT_Books.getModel().getValueAt(jT_Books.getSelectedRow(), 3)));
        publisher.setText((String) jT_Books.getModel().getValueAt(jT_Books.getSelectedRow(), 4));
        imgs.setText((String) jT_Books.getModel().getValueAt(jT_Books.getSelectedRow(), 5));
        imgm.setText((String) jT_Books.getModel().getValueAt(jT_Books.getSelectedRow(), 6));
        imgl.setText((String) jT_Books.getModel().getValueAt(jT_Books.getSelectedRow(), 7));
    }//GEN-LAST:event_jT_BooksMouseClicked

    private void jB_SolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_SolActionPerformed
        // TODO add your handling code here:

        if (sayac > 1) {
            sayac--;
        }
        jL_SayfaNo.setText(sayac + "/" + totalUsers);
        ShowUsers();

    }//GEN-LAST:event_jB_SolActionPerformed

    private void jB_SağActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_SağActionPerformed
        // TODO add your handling code here:
        if (sayac < totalUsers) {
            sayac++;
            jL_SayfaNo.setText(sayac + "/" + totalUsers);
            ShowUsers();
        }
    }//GEN-LAST:event_jB_SağActionPerformed

    private void jB_GitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_GitActionPerformed
        // TODO add your handling code here:
        if (Integer.parseInt(jT_Sayfa.getText()) < totalUsers && Integer.parseInt(jT_Sayfa.getText()) > 0) {
            sayac = Integer.parseInt(jT_Sayfa.getText());
            jL_SayfaNo.setText(sayac + "/" + totalUsers);
            ShowUsers();
        }
    }//GEN-LAST:event_jB_GitActionPerformed

    private void jB_FirstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_FirstActionPerformed
        // TODO add your handling code here:
        sayac = 1;
        jL_SayfaNo.setText(sayac + "/" + totalUsers);
        ShowUsers();
    }//GEN-LAST:event_jB_FirstActionPerformed

    private void jB_LastActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_LastActionPerformed
        // TODO add your handling code here:
        sayac = totalUsers;
        jL_SayfaNo.setText(sayac + "/" + totalUsers);
        ShowUsers();
    }//GEN-LAST:event_jB_LastActionPerformed

    private void jTabbedPane1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTabbedPane1MouseClicked
        // TODO add your handling code here:
        int x = jTabbedPane1.getSelectedIndex();
        switch (x) {
            case 0:
                ShowUsers();
                break;

            case 1:
                ShowBooks();
                break;

            default:
                System.out.println("tabbed - err");
                break;
        }
    }//GEN-LAST:event_jTabbedPane1MouseClicked

    private void jB_First1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_First1ActionPerformed
        // TODO add your handling code here:
        sayac2 = 1;
        jL_SayfaNo1.setText(sayac2 + "/" + totalBooks);
        ShowBooks();

    }//GEN-LAST:event_jB_First1ActionPerformed

    private void jB_Sol1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_Sol1ActionPerformed
        // TODO add your handling code here:
        if (sayac2 > 1) {
            sayac2--;
        }
        jL_SayfaNo1.setText(sayac2 + "/" + totalBooks);
        ShowBooks();
    }//GEN-LAST:event_jB_Sol1ActionPerformed

    private void jB_Sağ1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_Sağ1ActionPerformed
        // TODO add your handling code here:
        if (sayac2 < totalBooks) {
            sayac2++;
            jL_SayfaNo1.setText(sayac2 + "/" + totalBooks);
            ShowBooks();
        }
    }//GEN-LAST:event_jB_Sağ1ActionPerformed

    private void jB_Last1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_Last1ActionPerformed
        // TODO add your handling code here:
        sayac2 = totalBooks;
        jL_SayfaNo1.setText(sayac2 + "/" + totalBooks);
        ShowBooks();
    }//GEN-LAST:event_jB_Last1ActionPerformed

    private void jB_Git1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_Git1ActionPerformed
        // TODO add your handling code here:
        if (Integer.parseInt(jT_Sayfa1.getText()) < totalBooks && Integer.parseInt(jT_Sayfa1.getText()) > 0) {
            sayac2 = Integer.parseInt(jT_Sayfa1.getText());
            jL_SayfaNo1.setText(sayac2 + "/" + totalBooks);
            ShowUsers();
        }
        
    }//GEN-LAST:event_jB_Git1ActionPerformed

    private void jB_First1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jB_First1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jB_First1MouseClicked

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        DbConnect db = new DbConnect();
        dispose();
        Main main = new Main("ffe");
        main.setVisible(true);
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        DbConnect db = new DbConnect();
        dispose();
        Main main = new Main("ffe");
        main.setVisible(true);
    }//GEN-LAST:event_jButton8ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Admin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Books;
    private javax.swing.JPanel Users;
    private javax.swing.JTextField age;
    private javax.swing.JTextField author;
    private javax.swing.JTextField imgl;
    private javax.swing.JTextField imgm;
    private javax.swing.JTextField imgs;
    private javax.swing.JButton jB_First;
    private javax.swing.JButton jB_First1;
    private javax.swing.JButton jB_Git;
    private javax.swing.JButton jB_Git1;
    private javax.swing.JButton jB_Last;
    private javax.swing.JButton jB_Last1;
    private javax.swing.JButton jB_Sağ;
    private javax.swing.JButton jB_Sağ1;
    private javax.swing.JButton jB_Sol;
    private javax.swing.JButton jB_Sol1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jL_SayfaNo;
    private javax.swing.JLabel jL_SayfaNo1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jT_Books;
    private javax.swing.JTextField jT_Sayfa;
    private javax.swing.JTextField jT_Sayfa1;
    private javax.swing.JTable jT_Users;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField location;
    private javax.swing.JTextField password;
    private javax.swing.JTextField publisher;
    private javax.swing.JTextField title;
    private javax.swing.JTextField username;
    private javax.swing.JTextField year;
    private javax.swing.JTextField ısbn;
    // End of variables declaration//GEN-END:variables
}
